version: '3.8'

services:
  db:
    image: postgis/postgis:13-3.1
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tmsa_greentrack
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Syntaxe corrigée avec tiret
    ports:
      - "5432:5432"
    networks:
      - greentrack

  backend:
    build: ./backend
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app  # Syntaxe corrigée avec tiret
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/tmsa_greentrack
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - greentrack

  frontend:
    build: ./frontend
    container_name: react_container
    ports:
      - "3000:3000"  # Syntaxe corrigée avec tiret
    stdin_open: true
    tty: true

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "80:80"  # Syntaxe corrigée avec tiret
    depends_on:
      - db
    networks:
      - greentrack

volumes:
  postgres_data:  # Syntaxe correcte pour les volumes nommés

networks:
  greentrack:
    driver: bridge