# Generated by Django 4.2.16 on 2025-02-09 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aspect',
            fields=[
                ('id_aspect', models.AutoField(primary_key=True, serialize=False)),
                ('typeMilieu', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id_commune', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EngagementIndicateur',
            fields=[
                ('id_engagement_indicateur', models.AutoField(primary_key=True, serialize=False)),
                ('lieu_prelevement', models.CharField(max_length=255)),
                ('methode_equipement', models.CharField(max_length=255)),
                ('frequence', models.IntegerField()),
                ('responsabilite', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EntrepriseMere',
            fields=[
                ('id_entreprise_mere', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('statut_juridique', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PrefectureProvince',
            fields=[
                ('id_pref_prov', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('idUtilisateur', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('motDePasse', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='monitoring.utilisateur')),
            ],
            bases=('monitoring.utilisateur',),
        ),
        migrations.CreateModel(
            name='ResponsableEntreprise',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='monitoring.utilisateur')),
                ('id_entreprise_mere', models.IntegerField()),
                ('id_entreprise', models.IntegerField()),
            ],
            bases=('monitoring.utilisateur',),
        ),
        migrations.CreateModel(
            name='ResponsableSuiviTMSA',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='monitoring.utilisateur')),
                ('zone_de_suivi', models.CharField(max_length=255)),
            ],
            bases=('monitoring.utilisateur',),
        ),
        migrations.CreateModel(
            name='Suivi',
            fields=[
                ('idSuivi', models.AutoField(primary_key=True, serialize=False)),
                ('dateMesure', models.DateField()),
                ('valeurMesure', models.FloatField()),
                ('observations', models.TextField()),
                ('justificatif_etude', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('id_engagement_aspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.engagementindicateur')),
            ],
        ),
        migrations.CreateModel(
            name='Indicateur',
            fields=[
                ('id_indicateur', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('seuil_max', models.FloatField()),
                ('unite', models.CharField(max_length=100)),
                ('id_aspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.aspect')),
            ],
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id_entreprise', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('zone', models.CharField(max_length=255)),
                ('montantInvestissement', models.FloatField()),
                ('nombreEmploi', models.IntegerField()),
                ('superficieTotale', models.FloatField()),
                ('secteurDominant', models.CharField(max_length=255)),
                ('prefectureProvince', models.CharField(max_length=255)),
                ('DAE', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('EIE_PSSE', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('id_commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.commune')),
                ('id_entreprise_mere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring.entreprisemere')),
            ],
        ),
        migrations.AddField(
            model_name='engagementindicateur',
            name='id_entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.entreprise'),
        ),
        migrations.AddField(
            model_name='engagementindicateur',
            name='id_indicateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.indicateur'),
        ),
        migrations.AddField(
            model_name='commune',
            name='id_pref_prov',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.prefectureprovince'),
        ),
    ]
