# Generated by Django 4.2.16 on 2025-02-09 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_alter_admin_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entreprise',
            old_name='montantInvestissement',
            new_name='montant_investissement',
        ),
        migrations.RenameField(
            model_name='entreprise',
            old_name='nombreEmploi',
            new_name='nombre_emploi',
        ),
        migrations.RenameField(
            model_name='entreprise',
            old_name='prefectureProvince',
            new_name='prefecture_province',
        ),
        migrations.RenameField(
            model_name='entreprise',
            old_name='secteurDominant',
            new_name='secteur_dominant',
        ),
        migrations.RenameField(
            model_name='entreprise',
            old_name='superficieTotale',
            new_name='superficie_totale',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$kMa0GCrNJJzcuSAtZEPtjG$XFlH5rLIrBGs7PUT4KhNX0QompLbIIGcITgvV1ygWPA=', max_length=100),
        ),
    ]
