# Generated by Django 4.2.16 on 2025-02-10 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_rename_montantinvestissement_entreprise_montant_investissement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$4kRPHls9i24D1np4f1LRbd$3Bf2LXd0K5ekzuLIY2EMRYjrV1M+xzNzdDKSRTHwwK8=', max_length=100),
        ),
        migrations.CreateModel(
            name='Echeance',
            fields=[
                ('id_echeance', models.AutoField(primary_key=True, serialize=False)),
                ('date_prevue', models.DateField()),
                ('statut', models.CharField(choices=[('en attente', 'En attente'), ('effectuee', 'Effectuée')], default='en attente', max_length=50)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeances', to='monitoring.engagementindicateur')),
                ('suivi', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='echeance_associee', to='monitoring.suivi')),
            ],
        ),
        migrations.AddField(
            model_name='suivi',
            name='echeance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suivi_associe', to='monitoring.echeance'),
        ),
    ]
