# Generated by Django 4.2.16 on 2025-02-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_alter_utilisateur_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suivi',
            old_name='echeance',
            new_name='id_echeance',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$dYYn6ZkWshWU9Z2GT2JEFp$2Ecv+cStwR2hfX9WY2Oc78gopDSUueWt4qA0Axc4PLk=', max_length=100),
        ),
    ]
