# Generated by Django 4.2.16 on 2025-02-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_rename_echeance_suivi_id_echeance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='echeance',
            name='suivi',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$600000$lQsrTOT4VWhR1UoYUH0c0s$uW4tvSXWWT5eMAqbLjFXP63GduvfXKxkzah8zodYBl4=', max_length=100),
        ),
    ]
