# Generated by Django 4.2.16 on 2025-02-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_remove_echeance_suivi_alter_utilisateur_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsableentreprise',
            name='id_entreprise',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='responsableentreprise',
            name='id_entreprise_mere',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='responsablesuivitmsa',
            name='zone_de_suivi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='idUtilisateur',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
