# Generated by Django 4.2.16 on 2025-02-10 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_alter_responsableentreprise_id_entreprise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsableentreprise',
            name='id_entreprise_mere',
        ),
    ]
