# Generated by Django 4.2.16 on 2025-02-10 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0009_remove_responsableentreprise_id_entreprise_mere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsableentreprise',
            name='id_entreprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring.entreprise'),
        ),
    ]
