# Generated by Django 4.2.16 on 2025-02-10 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0010_alter_responsableentreprise_id_entreprise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='echeance',
            old_name='date_prevue',
            new_name='date_limite',
        ),
        migrations.RenameField(
            model_name='suivi',
            old_name='dateMesure',
            new_name='date_mesure',
        ),
        migrations.RenameField(
            model_name='suivi',
            old_name='id_echeance',
            new_name='echeance',
        ),
        migrations.RenameField(
            model_name='suivi',
            old_name='idSuivi',
            new_name='id_suivi',
        ),
        migrations.RenameField(
            model_name='suivi',
            old_name='valeurMesure',
            new_name='valeur_mesure',
        ),
        migrations.RemoveField(
            model_name='echeance',
            name='engagement',
        ),
        migrations.RemoveField(
            model_name='engagementindicateur',
            name='frequence',
        ),
        migrations.RemoveField(
            model_name='engagementindicateur',
            name='lieu_prelevement',
        ),
        migrations.RemoveField(
            model_name='engagementindicateur',
            name='methode_equipement',
        ),
        migrations.RemoveField(
            model_name='engagementindicateur',
            name='responsabilite',
        ),
        migrations.AlterField(
            model_name='engagementindicateur',
            name='id_entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='monitoring.entreprise'),
        ),
        migrations.AlterField(
            model_name='engagementindicateur',
            name='id_indicateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='monitoring.indicateur'),
        ),
        migrations.AlterField(
            model_name='suivi',
            name='justificatif_etude',
            field=models.FileField(blank=True, null=True, upload_to='justificatifs/'),
        ),
        migrations.AlterField(
            model_name='suivi',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EngagementAspect',
            fields=[
                ('id_engagement_aspect', models.AutoField(primary_key=True, serialize=False)),
                ('lieu_prelevement', models.CharField(max_length=255)),
                ('methode_equipement', models.CharField(max_length=255)),
                ('frequence', models.IntegerField()),
                ('responsabilite', models.CharField(max_length=255)),
                ('date_creation', models.DateField()),
                ('id_engagement_indicateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aspects', to='monitoring.engagementindicateur')),
            ],
        ),
        migrations.AddField(
            model_name='echeance',
            name='id_engagement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='echeances', to='monitoring.engagementaspect'),
        ),
        migrations.AlterField(
            model_name='suivi',
            name='id_engagement_aspect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='monitoring.engagementaspect'),
        ),
    ]
