# Generated by Django 4.2.16 on 2025-02-10 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0011_rename_date_prevue_echeance_date_limite_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='echeance',
            old_name='id_engagement',
            new_name='id_engagement_aspect',
        ),
    ]
