# Generated by Django 4.2.16 on 2025-02-11 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0012_rename_id_engagement_echeance_id_engagement_aspect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engagementaspect',
            name='id_engagement_indicateur',
        ),
        migrations.AddField(
            model_name='engagementindicateur',
            name='id_engagement_aspect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aspects', to='monitoring.engagementaspect'),
        ),
    ]
