# Generated by Django 4.2.16 on 2025-02-11 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0013_remove_engagementaspect_id_engagement_indicateur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suivi',
            name='observations',
        ),
        migrations.RemoveField(
            model_name='suivi',
            name='valeur_mesure',
        ),
        migrations.CreateModel(
            name='SuiviIndicateur',
            fields=[
                ('id_suivi_indicateur', models.AutoField(primary_key=True, serialize=False)),
                ('valeur_mesure', models.FloatField()),
                ('observations', models.TextField(blank=True, null=True)),
                ('engagement_indicateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.engagementindicateur')),
                ('suivi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivi_indicateurs', to='monitoring.suivi')),
            ],
        ),
    ]
