# Generated by Django 4.2.16 on 2025-02-11 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0014_remove_suivi_observations_remove_suivi_valeur_mesure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engagementindicateur',
            name='id_entreprise',
        ),
        migrations.AddField(
            model_name='engagementaspect',
            name='id_entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='monitoring.entreprise'),
        ),
    ]
