# Generated by Django 4.2.16 on 2025-02-11 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0015_remove_engagementindicateur_id_entreprise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementaspect',
            name='id_entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engagements_aspects', to='monitoring.entreprise'),
        ),
    ]
