# Generated by Django 4.2.16 on 2025-02-11 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0016_alter_engagementaspect_id_entreprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementindicateur',
            name='id_indicateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements_indicateurs', to='monitoring.indicateur'),
        ),
    ]
