# Generated by Django 4.2.16 on 2025-02-11 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0017_alter_engagementindicateur_id_indicateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementindicateur',
            name='id_engagement_aspect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engagements_indicateurs', to='monitoring.engagementaspect'),
        ),
        migrations.AlterField(
            model_name='engagementindicateur',
            name='id_indicateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.indicateur'),
        ),
        migrations.AddConstraint(
            model_name='engagementindicateur',
            constraint=models.UniqueConstraint(fields=('id_engagement_aspect', 'id_indicateur'), name='unique_engagement_aspect_indicateur'),
        ),
    ]
