# Generated by Django 4.2.16 on 2025-02-11 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0018_alter_engagementindicateur_id_engagement_aspect_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='admin',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='responsableentreprise',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='responsablesuivitmsa',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='utilisateur',
            managers=[
            ],
        ),
    ]
