# Generated by Django 4.2.16 on 2025-02-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0019_alter_admin_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suivi',
            name='echeance',
        ),
        migrations.AddField(
            model_name='engagementaspect',
            name='date_prochaine_echeance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suivi',
            name='date_limite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suivi',
            name='statut',
            field=models.CharField(choices=[('en attente', 'En attente'), ('effectué', 'Effectué'), ('effectué_Retard', 'Effectué_Retard')], default='en attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='suivi',
            name='date_mesure',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Echeance',
        ),
    ]
