# Generated by Django 4.2.16 on 2025-02-13 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0021_engagementaspect_id_aspect_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suivi',
            name='cloturer',
            field=models.BooleanField(default=False),
        ),
    ]
