# Generated by Django 4.2.16 on 2025-02-14 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0022_suivi_cloturer'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='suiviindicateur',
            constraint=models.UniqueConstraint(fields=('suivi', 'engagement_indicateur'), name='unique_suivi_engagement_indicateur'),
        ),
    ]
