# Generated by Django 4.2.16 on 2025-02-20 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0023_suiviindicateur_unique_suivi_engagement_indicateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiviteIndustrielle',
            fields=[
                ('id_activite', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EngagementIndicateurSousAspect',
            fields=[
                ('id_engagement_indicateur_sous_aspect', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='EngagementSousAspectEauPollution',
            fields=[
                ('id_engagement_sous_aspect', models.AutoField(primary_key=True, serialize=False)),
                ('lieu_prelevement', models.CharField(max_length=255)),
                ('methode_equipement', models.CharField(max_length=255)),
                ('frequence', models.IntegerField(choices=[(1, 'Mensuel (12 fois par an)'), (2, 'Trimestriel (4 fois par an)'), (3, 'Semestriel (2 fois par an)'), (4, 'Bisannuel (1 fois par 2 ans)'), (5, 'Triennal (1 fois par 3 ans)')])),
                ('responsabilite', models.CharField(max_length=255)),
                ('date_creation', models.DateField()),
                ('date_prochaine_echeance', models.DateField(blank=True, null=True)),
                ('id_entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='SecteurActivite',
            fields=[
                ('id_secteur', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SousAspectEauPollution',
            fields=[
                ('id_sous_aspect', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='engagementaspect',
            name='frequence',
            field=models.IntegerField(choices=[(1, 'Mensuel (12 fois par an)'), (2, 'Trimestriel (4 fois par an)'), (3, 'Semestriel (2 fois par an)'), (4, 'Bisannuel (1 fois par 2 ans)'), (5, 'Triennal (1 fois par 3 ans)')]),
        ),
        migrations.CreateModel(
            name='SuiviSousAspect',
            fields=[
                ('id_suivi_sous_aspect', models.AutoField(primary_key=True, serialize=False)),
                ('date_mesure', models.DateField(blank=True, null=True)),
                ('date_limite', models.DateField(blank=True, null=True)),
                ('justificatif_etude', models.FileField(blank=True, null=True, upload_to='justificatifs/')),
                ('statut', models.CharField(choices=[('en attente', 'En attente'), ('effectué', 'Effectué'), ('effectué_Retard', 'Effectué_Retard')], default='en attente', max_length=20)),
                ('id_engagement_sous_aspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='monitoring.engagementsousaspecteaupollution')),
            ],
        ),
        migrations.CreateModel(
            name='SuiviIndicateurSousAspect',
            fields=[
                ('id_suivi_indicateur_sous_aspect', models.AutoField(primary_key=True, serialize=False)),
                ('valeur_mesure', models.FloatField()),
                ('observations', models.TextField(blank=True, null=True)),
                ('engagement_indicateur_sous_aspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.engagementindicateursousaspect')),
                ('suivi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivi_indicateurs', to='monitoring.suivisousaspect')),
            ],
        ),
        migrations.CreateModel(
            name='IndicateurEauPollution',
            fields=[
                ('id_indicateur_eaupollution', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('seuil_max', models.FloatField()),
                ('unite', models.CharField(max_length=100)),
                ('code_MICNT', models.IntegerField()),
                ('id_activite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.activiteindustrielle')),
                ('id_sous_aspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.sousaspecteaupollution')),
            ],
        ),
        migrations.AddField(
            model_name='engagementsousaspecteaupollution',
            name='id_sous_aspect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.sousaspecteaupollution'),
        ),
        migrations.AddField(
            model_name='engagementindicateursousaspect',
            name='id_engagement_sous_aspect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements_indicateurs', to='monitoring.engagementsousaspecteaupollution'),
        ),
        migrations.AddField(
            model_name='engagementindicateursousaspect',
            name='id_indicateur_eaupollution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.indicateureaupollution'),
        ),
        migrations.AddField(
            model_name='activiteindustrielle',
            name='id_secteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='monitoring.secteuractivite'),
        ),
        migrations.AddConstraint(
            model_name='suiviindicateursousaspect',
            constraint=models.UniqueConstraint(fields=('suivi', 'engagement_indicateur_sous_aspect'), name='unique_suivi_indicateur_sous_aspect'),
        ),
        migrations.AddConstraint(
            model_name='engagementsousaspecteaupollution',
            constraint=models.UniqueConstraint(fields=('id_sous_aspect',), name='unique_engagement_sous-aspect'),
        ),
        migrations.AddConstraint(
            model_name='engagementindicateursousaspect',
            constraint=models.UniqueConstraint(fields=('id_engagement_sous_aspect', 'id_indicateur_eaupollution'), name='unique_engagement_sous_aspect_indicateur'),
        ),
    ]
