# Generated by Django 4.2.16 on 2025-02-20 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0025_sousaspecteaupollution_aspect'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspect',
            name='est_eau',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SousAspectEau',
            fields=[
                ('id_sous_aspect', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('est_pollution', models.BooleanField(default=False)),
                ('aspect', models.ForeignKey(limit_choices_to={'typeMilieu': 'Eau'}, on_delete=django.db.models.deletion.CASCADE, to='monitoring.aspect')),
            ],
        ),
        migrations.AddField(
            model_name='engagementaspect',
            name='id_sous_aspect_eau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring.sousaspecteau'),
        ),
        migrations.AlterField(
            model_name='engagementsousaspecteaupollution',
            name='id_sous_aspect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.sousaspecteau'),
        ),
        migrations.AlterField(
            model_name='indicateureaupollution',
            name='id_sous_aspect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.sousaspecteau'),
        ),
        migrations.DeleteModel(
            name='SousAspectEauPollution',
        ),
    ]
