# Generated by Django 4.2.16 on 2025-02-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0027_remove_engagementaspect_unique_engagement_aspect_aspect_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sousaspecteau',
            name='est_pollution',
            field=models.BooleanField(),
        ),
    ]
