# Generated by Django 4.2.16 on 2025-02-20 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0029_suivisousaspect_cloturer'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='engagementaspect',
            name='unique_engagement_aspect_aspect',
        ),
        migrations.AddConstraint(
            model_name='engagementaspect',
            constraint=models.UniqueConstraint(condition=models.Q(('id_sous_aspect_eau__isnull', False)), fields=('id_aspect', 'id_sous_aspect_eau'), name='unique_engagement_aspect_aspect'),
        ),
    ]
