# Generated by Django 4.2.16 on 2025-02-21 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0030_remove_engagementaspect_unique_engagement_aspect_aspect_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='id_activite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring.activiteindustrielle'),
        ),
    ]
