# Generated by Django 4.2.16 on 2025-02-22 16:39

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0031_entreprise_id_activite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id_parcelle', models.AutoField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.AddField(
            model_name='entreprise',
            name='id_parcelle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.parcelle'),
        ),
    ]
