# Generated by Django 4.2.16 on 2025-02-22 20:14

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0033_alter_parcelle_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelle',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=26191),
        ),
    ]
