# Generated by Django 4.2.16 on 2025-02-22 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0035_alter_entreprise_dae_alter_entreprise_eie_psse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entreprise',
            name='secteur_dominant',
        ),
    ]
