# Generated by Django 4.2.16 on 2025-02-22 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0036_remove_entreprise_secteur_dominant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entreprise',
            name='prefecture_province',
        ),
    ]
