# Generated by Django 4.2.16 on 2025-02-22 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0037_remove_entreprise_prefecture_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='id_parcelle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.parcelle', unique=True),
        ),
    ]
