# Generated by Django 4.2.16 on 2025-02-22 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0038_alter_entreprise_id_parcelle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='id_parcelle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitoring.parcelle'),
        ),
    ]
