# Generated by Django 4.2.16 on 2025-02-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0040_zone_remove_entreprise_zone_entreprise_id_zone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelle',
            name='x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
