# Generated by Django 4.2.16 on 2025-02-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0041_parcelle_x_parcelle_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='Avenue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='Regime',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='Rue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='Secteur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='lot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='nom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
