# Generated by Django 4.2.16 on 2025-02-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0043_rename_avenue_entreprise_avenue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='Ilot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
