# Generated by Django 4.2.16 on 2025-02-26 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0044_entreprise_ilot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responsablesuivitmsa',
            old_name='zone_de_suivi',
            new_name='id_zone',
        ),
    ]
