# Generated by Django 4.2.16 on 2025-02-26 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0045_rename_zone_de_suivi_responsablesuivitmsa_id_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsablesuivitmsa',
            name='id_zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring.zone'),
        ),
    ]
