# Generated by Django 4.2.16 on 2025-02-27 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0046_alter_responsablesuivitmsa_id_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='id_commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring.commune'),
        ),
    ]
