# Generated by Django 4.2.16 on 2025-02-28 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0047_alter_entreprise_id_commune'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sousaspecteau',
            name='aspect',
            field=models.ForeignKey(limit_choices_to={'est_eau': True}, on_delete=django.db.models.deletion.CASCADE, to='monitoring.aspect'),
        ),
    ]
