# Generated by Django 4.2.16 on 2025-02-28 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0048_alter_sousaspecteau_aspect'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementIndicateurSousAspectPollution',
            fields=[
                ('id_engagement_indicateur_sous_aspect', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='EngagementSousAspect',
            fields=[
                ('id_engagement_sous_aspect', models.AutoField(primary_key=True, serialize=False)),
                ('lieu_prelevement', models.CharField(max_length=255)),
                ('methode_equipement', models.CharField(max_length=255)),
                ('frequence', models.IntegerField()),
                ('responsabilite', models.CharField(max_length=255)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_prochaine_echeance', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndicateurSousAspect',
            fields=[
                ('id_indicateur_sous_aspect', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('seuil_max', models.FloatField()),
                ('unite', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SuiviIndicateurSousAspectPollution',
            fields=[
                ('id_suivi_indicateur_sous_aspect', models.AutoField(primary_key=True, serialize=False)),
                ('valeur_mesure', models.FloatField()),
                ('observations', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuiviSousAspectPollution',
            fields=[
                ('id_suivi_sous_aspect', models.AutoField(primary_key=True, serialize=False)),
                ('date_mesure', models.DateField(blank=True, null=True)),
                ('date_limite', models.DateField(blank=True, null=True)),
                ('justificatif_etude', models.FileField(blank=True, null=True, upload_to='justificatifs/')),
                ('statut', models.CharField(choices=[('en attente', 'En attente'), ('effectué', 'Effectué'), ('effectué_Retard', 'Effectué_Retard')], default='en attente', max_length=20)),
                ('cloturer', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='engagementindicateursousaspect',
            name='unique_engagement_sous_aspect_indicateur',
        ),
        migrations.RemoveField(
            model_name='engagementindicateursousaspect',
            name='id_indicateur_eaupollution',
        ),
        migrations.AddField(
            model_name='suivisousaspectpollution',
            name='id_engagement_sous_aspect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='monitoring.engagementsousaspecteaupollution'),
        ),
        migrations.AddField(
            model_name='suiviindicateursousaspectpollution',
            name='engagement_indicateur_sous_aspect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.engagementindicateursousaspectpollution'),
        ),
        migrations.AddField(
            model_name='suiviindicateursousaspectpollution',
            name='suivi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivi_indicateurs', to='monitoring.suivisousaspectpollution'),
        ),
        migrations.AddField(
            model_name='indicateursousaspect',
            name='id_sous_aspect',
            field=models.ForeignKey(limit_choices_to={'est_pollution': False}, on_delete=django.db.models.deletion.CASCADE, to='monitoring.sousaspecteau'),
        ),
        migrations.AddField(
            model_name='engagementsousaspect',
            name='id_entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.entreprise'),
        ),
        migrations.AddField(
            model_name='engagementsousaspect',
            name='id_sous_aspect',
            field=models.ForeignKey(limit_choices_to={'est_pollution': False}, on_delete=django.db.models.deletion.CASCADE, to='monitoring.sousaspecteau'),
        ),
        migrations.AddField(
            model_name='engagementindicateursousaspectpollution',
            name='id_engagement_sous_aspect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements_indicateurs', to='monitoring.engagementsousaspecteaupollution'),
        ),
        migrations.AddField(
            model_name='engagementindicateursousaspectpollution',
            name='id_indicateur_eaupollution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.indicateureaupollution'),
        ),
        migrations.AddField(
            model_name='engagementindicateursousaspect',
            name='id_indicateur_sous_aspect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring.indicateursousaspect'),
        ),
        migrations.AlterField(
            model_name='engagementindicateursousaspect',
            name='id_engagement_sous_aspect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.engagementsousaspect'),
        ),
        migrations.AlterField(
            model_name='suivisousaspect',
            name='id_engagement_sous_aspect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='monitoring.engagementsousaspect'),
        ),
        migrations.AddConstraint(
            model_name='suiviindicateursousaspectpollution',
            constraint=models.UniqueConstraint(fields=('suivi', 'engagement_indicateur_sous_aspect'), name='unique_suivi_indicateur_sous_aspectpollution'),
        ),
        migrations.AddConstraint(
            model_name='engagementindicateursousaspectpollution',
            constraint=models.UniqueConstraint(fields=('id_engagement_sous_aspect', 'id_indicateur_eaupollution'), name='unique_engagement_sous_aspect_indicateur'),
        ),
    ]
