# Generated by Django 4.2.16 on 2025-03-04 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0049_engagementindicateursousaspectpollution_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='engagementaspect',
            name='unique_engagement_aspect_aspect',
        ),
        migrations.AlterField(
            model_name='indicateur',
            name='id_aspect',
            field=models.ForeignKey(limit_choices_to={'est_eau': False}, on_delete=django.db.models.deletion.CASCADE, to='monitoring.aspect'),
        ),
        migrations.AddConstraint(
            model_name='engagementaspect',
            constraint=models.UniqueConstraint(condition=models.Q(('id_sous_aspect_eau__isnull', True)), fields=('id_entreprise', 'id_aspect'), name='unique_engagement_aspect_entreprise_aspect'),
        ),
        migrations.AddConstraint(
            model_name='engagementaspect',
            constraint=models.UniqueConstraint(condition=models.Q(('id_sous_aspect_eau__isnull', False)), fields=('id_entreprise', 'id_aspect', 'id_sous_aspect_eau'), name='unique_engagement_aspect_entreprise_aspect_sous_aspect'),
        ),
    ]
